#!/home/keno/.rvm/rubies/ruby-1.9.2-p320/bin/ruby

$LOAD_PATH << "#{File.expand_path('..',__FILE__)}/lib"

require 'veewee'
require 'vagrant'
require 'jbox/cli'

env = Veewee::Environment.new

begin
    # Begin logging
    env.ui.info("jbox") { "`jbox` invoked: #{ARGV.inspect}" }
    
    # Disable color if the proper argument was passed
    shell = ARGV.include?("--no-color") ? Thor::Shell::Basic.new : Thor::Base.shell.new
    
    # Attach the veewee ui
    env.ui = ::Veewee::UI::Shell.new(env, shell)
    env.load!
    
    # Start the Veewee CLI
    ::Veewee::CLI.start(ARGV, :env => env)
rescue Veewee::Error => e
    env.ui.error "#{e}"
end
